Repository ezenormey/devops-aula07, pull requests merged in 2018-10, with the labels that each got.

#2 Integrar requisitos v1.0
  docs/requisitos.md
Labels: análise

#4 Integrar arquitetura v1.0
  docs/arquitetura.md
Labels: arquitetura

#6 Integrar implementação v1.0
  src/jogovelha.py
Labels: programação

#8 Integrar testes V1.0
  src/testes_inic.py
  src/testes_jogar.py
Labels: testes

#9 Gerar release v1.0
  docs/arquitetura.md
  docs/requisitos.md
  src/jogovelha.py
  src/testes_inic.py
  src/testes_jogar.py
Labels: operações

#11 Integrar requisitos v1.1
  docs/requisitos.md
Labels: análise

#14 Integrar arquitetura v1.1
  docs/arquitetura.md
Labels: arquitetura

#16 Integrar testes v1.0
  src/testes_inic.py
Labels: testes

#17 Update jogovelha.py
  src/jogovelha.py
Labels: programação

#18 Gerar release v1.1
  docs/arquitetura.md
  docs/requisitos.md
  src/jogovelha.py
  src/testes_inic.py
Labels: operações
